# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  roombyapirooms:
    image: roombyapirooms
    build:
      context: .
      dockerfile: Roomby.API.Rooms/Dockerfile
    ports:
      - 80
